apiVersion: apps/v1
kind: Deployment
metadata:
  name: NotificationManagement
  labels:
    app: NotificationManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NotificationManagement
  template:
    metadata:
      labels:
        app: NotificationManagement
    spec:
      containers:
        - name: NotificationManagement
          image: username/NotificationManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5