apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentmanagement
  labels:
    app: paymentmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentmanagement
  template:
    metadata:
      labels:
        app: paymentmanagement
    spec:
      containers:
        - name: paymentmanagement
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          image: skcc13acr.azurecr.io/paymentmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5