apiVersion: apps/v1
kind: Deployment
metadata:
  name: OrderDeliveryManagement
  labels:
    app: OrderDeliveryManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderDeliveryManagement
  template:
    metadata:
      labels:
        app: OrderDeliveryManagement
    spec:
      containers:
        - name: OrderDeliveryManagement
          image: username/OrderDeliveryManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5