apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: paymentmanagement
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: paymentmanagement
  targetCPUUtilizationPercentage: 25