apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketingmanagement
  labels:
    app: marketingmanagement
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marketingmanagement
  template:
    metadata:
      labels:
        app: marketingmanagement
    spec:
      containers:
        - name: marketingmanagement
          image: skcc13acr.azurecr.io/marketingmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5