apiVersion: apps/v1
kind: Deployment
metadata:
  name: MarketingManagement
  labels:
    app: MarketingManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MarketingManagement
  template:
    metadata:
      labels:
        app: MarketingManagement
    spec:
      containers:
        - name: MarketingManagement
          image: username/MarketingManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5